name: github-actions-ci/cd

on:
  push:
    branches: [deploy_kyuchul, deploy_jaewon, deploy_jinhyuk, deploy_deaung]

jobs:
  print-test:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{
        github.ref_name == 'deploy_kyuchul' && secrets.DOCKER_USERNAME_KYUCHUL  ||
        github.ref_name == 'deploy_jaewon' && secrets.DOCKER_USERNAME_JAEWON  ||
        github.ref_name == 'deploy_jinhyuk' && secrets.DOCKER_USERNAME_JINHYUK  ||
        github.ref_name == 'deploy_deaung' && secrets.DOCKER_USERNAME_DEAUNG
        }}
      DOCKER_PASSWORD: ${{
        github.ref_name == 'deploy_kyuchul' && secrets.DOCKER_PASSWORD_KYUCHUL  ||
        github.ref_name == 'deploy_jaewon' && secrets.DOCKER_PASSWORD_JAEWON  ||
        github.ref_name == 'deploy_jinhyuk' && secrets.DOCKER_PASSWORD_JINHYUK  ||
        github.ref_name == 'deploy_deaung' && secrets.DOCKER_PASSWORD_DEAUNG
        }}
      APPLICATION_SECRET: ${{
        github.ref_name == 'deploy_kyuchul' && secrets.DOCKER_SECRET_KYUCHUL  ||
        github.ref_name == 'deploy_jaewon' && secrets.DOCKER_SECRET_JAEWON  ||
        github.ref_name == 'deploy_jinhyuk' && secrets.DOCKER_SECRET_JINHYUK  ||
        github.ref_name == 'deploy_deaung' && secrets.DOCKER_SECRET_DEAUNG
        }}
      REACT_ENV: ${{
        github.ref_name == 'deploy_kyuchul' && secrets.REACT_ENV_KYUCHUL  ||
        github.ref_name == 'deploy_jaewon' && secrets.REACT_ENV_JAEWON  ||
        github.ref_name == 'deploy_jinhyuk' && secrets.REACT_ENV_JINHYUK  ||
        github.ref_name == 'deploy_deaung' && secrets.REACT_ENV_DEAUNG
        }}
        
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.ref }}

      - name: docker login
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: install JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: build spring boot app
        run: |
          cd nomore_back
          echo ${{ env.APPLICATION_SECRET }} | base64 --decode > ./src/main/resources/application-secret.yml
          chmod 777 ./mvnw
          ./mvnw clean package -DskipTests
          docker build -t ${{ env.DOCKER_USERNAME }}/spring-app:latest .
          docker push ${{ env.DOCKER_USERNAME }}/spring-app:latest

      - name: build react app
        run: |
          cd nomore_front
          echo ${{ env.REACT_ENV }} | base64 --decode > ./.env
          npm install
          npm run build
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest
